server:
  port: 8083

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
            exposedHeaders:
              - "Authorization"
            maxAge: 3600
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
          filters:
            # Verwijder de RewritePath filter om de originele URL structuur te behouden
            - DedupeResponseHeader=Access-Control-Allow-Origin
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/review/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comment/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
    instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
