version: '3.8'

services:
  # Database voor Postservice
  postservice-db:
    image: mysql:8.0
    container_name: postservice-db
    ports:
      - "3307:3306"
    volumes:
      - db_data_postservice:/var/lib/mysql

  # Database voor Reviewservice
  reviewservice-db:
    image: mysql:8.0
    container_name: reviewservice-db
    ports:
      - "3308:3306"
    volumes:
      - db_data_reviewservice:/var/lib/mysql

  # Database voor Commentservice
  commentservice-db:
    image: mysql:8.0
    container_name: commentservice-db
    ports:
      - "3309:3306"
    volumes:
      - db_data_commentservice:/var/lib/mysql

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP port voor messaging
      - "15672:15672"  # Management console port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

# Declaratie van volumes voor persistente opslag
volumes:
  db_data_postservice:
  db_data_reviewservice:
  db_data_commentservice:
  rabbitmq_data:
